language: ruby
rvm:
  - 1.9.3
  - 1.8.7
  - jruby-19mode
env:
  - CAPYBARA_DEFAULT_DRIVER=rack_test
  - CAPYBARA_DEFAULT_DRIVER=poltergeist
  - CAPYBARA_DEFAULT_DRIVER=selenium
  - CAPYBARA_DEFAULT_DRIVER=webkit
before_install:
  - wget http://phantomjs.googlecode.com/files/phantomjs-1.7.0-linux-i686.tar.bz2
  - tar -xf phantomjs-1.7.0-linux-i686.tar.bz2
  - sudo rm -rf /usr/local/phantomjs
  - sudo mv phantomjs-1.7.0-linux-i686 /usr/local/phantomjs
before_script:
  - 'bundle'
script: 'bundle exec rspec'


